import { Proposal, Meeting } from "@/types";

export async function exportToPDF(meeting: Meeting, proposals: Proposal[]): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  // Header
  doc.setFillColor(26, 26, 26);
  doc.rect(0, 0, 297, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("CEC Meeting Minutes", 14, 11);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${meeting.meeting_code}  ·  ${new Date(meeting.date).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}`, 14, 18);
  doc.text(`IDLC Finance PLC — Credit Evaluation Committee`, 14, 24);

  // Summary boxes
  doc.setTextColor(44, 44, 44);
  const summaryY = 35;
  const summaryItems = [
    { label: "Total", value: meeting.summary.total },
    { label: "Approved", value: meeting.summary.approved },
    { label: "Board Pending", value: meeting.summary.board_pending },
    { label: "Deferred", value: meeting.summary.deferred },
    { label: "Declined", value: meeting.summary.declined },
  ];
  summaryItems.forEach((item, i) => {
    const x = 14 + i * 55;
    doc.setFillColor(250, 250, 248);
    doc.roundedRect(x, summaryY, 50, 14, 2, 2, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(String(item.value), x + 5, summaryY + 9);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(107, 107, 107);
    doc.text(item.label, x + 5, summaryY + 13);
    doc.setTextColor(44, 44, 44);
  });

  // Proposals table
  const tableData = proposals.map((p) => [
    p.proposal_code,
    p.client_name,
    p.division,
    p.category,
    p.cumulative_exposure != null
      ? `BDT ${p.cumulative_exposure} Cr`
      : p.current_outstanding != null
      ? `BDT ${p.current_outstanding} Cr`
      : "—",
    p.irg_grade ?? "—",
    p.cib_status ?? "—",
    p.resolution,
    p.resolution_note
      ? p.resolution_note.length > 60
        ? p.resolution_note.substring(0, 60) + "…"
        : p.resolution_note
      : "—",
  ]);

  autoTable(doc, {
    startY: summaryY + 20,
    head: [["Code", "Client", "Division", "Category", "Exposure", "IRG", "CIB", "Resolution", "Notes"]],
    body: tableData,
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [26, 26, 26], textColor: 255, fontSize: 7 },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 35 },
      2: { cellWidth: 22 },
      3: { cellWidth: 22 },
      4: { cellWidth: 22 },
      5: { cellWidth: 15 },
      6: { cellWidth: 15 },
      7: { cellWidth: 22 },
      8: { cellWidth: "auto" },
    },
    didParseCell: (data) => {
      if (data.column.index === 7) {
        const val = data.cell.raw as string;
        if (val === "Approved") data.cell.styles.textColor = [21, 128, 61];
        else if (val === "Approved (Board)") data.cell.styles.textColor = [124, 58, 237];
        else if (val === "Deferred") data.cell.styles.textColor = [180, 83, 9];
        else if (val === "Declined") data.cell.styles.textColor = [232, 32, 42];
      }
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(154, 154, 154);
    doc.text(
      `Generated by CEC Visualizer · IDLC Finance PLC · Page ${i} of ${pageCount}`,
      148.5,
      205,
      { align: "center" }
    );
  }

  doc.save(`${meeting.meeting_code}_Minutes.pdf`);
}
